let characters = [
    {
        characterName: "Donkey Kong",
        yamlOptionName: 'Donkey',
        firstColorIndexInYamlOption: 1,
        additionalInfoOrInstructions: "",
        buttonColor: "#ffe572",
        buttonOutline: "#854b1b",
        buttonFontColor: "#111111",
        backgroundColorInCanvas: "#fffcd6",
        backgroundColor: "#ffebb3",
        palettes: [
            {
                name: "DKC Default",
                colors: [
                    "#181000",
                    "#402000",
                    "#603000",
                    "#884000",
                    "#A85000",
                    "#C06000",
                    "#D07000",
                    "#F80000",
                    "#800000",
                    "#983000",
                    "#F88070",
                    "#F8A090",
                    "#F8C0B8",
                    "#F8E0D8",
                    "#F8F8F8",
                ]
            },
            {
                name: "DKC Default (Inactive)",
                colors: [
                    '#181808',
                    '#392008',
                    '#522908',
                    '#6A3908',
                    '#8B4108',
                    '#9C5208',
                    '#AC6208',
                    '#CD0808',
                    '#6A0808',
                    '#7B2908',
                    '#C56A5A',
                    '#C5837B',
                    '#C59C94',
                    '#C5B4AC',
                    '#CDCDCD',
                ]
            },
            {
                name: "DKC Team 2",
                colors: [
                    '#181000',
                    '#412000',
                    '#623100',
                    '#8B4100',
                    '#AC5200',
                    '#C56200',
                    '#D57300',
                    '#FFE600',
                    '#AC7300',
                    '#9C3100',
                    '#FF8373',
                    '#FFA494',
                    '#FFC5BD',
                    '#FFE6DE',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC Team 2 (Inactive)",
                colors: [
                    '#181808',
                    '#392008',
                    '#522908',
                    '#6A3908',
                    '#8B4108',
                    '#9C5208',
                    '#AC6208',
                    '#CDB408',
                    '#8B5A08',
                    '#7B2908',
                    '#C56A5A',
                    '#C5837B',
                    '#C59C94',
                    '#C5B4AC',
                    '#CDCDCD',
                ]
            },
            {
                name: "DKC2 Diddy Team 2",
                colors: [
                    '#181000',
                    '#412000',
                    '#623100',
                    '#8B4100',
                    '#AC5200',
                    '#C56200',
                    '#D57300',
                    '#CD62EE',
                    '#7B31D5',
                    '#9C3100',
                    '#FF8373',
                    '#FFA494',
                    '#FFC5BD',
                    '#FFE6DE',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC3 Kiddy",
                colors: [
                    '#181000',
                    '#412000',
                    '#623100',
                    '#8B4100',
                    '#AC5200',
                    '#C56200',
                    '#D57300',
                    '#52BDF6',
                    '#5A6AAC',
                    '#9C3100',
                    '#FF8373',
                    '#FFA494',
                    '#FFC5BD',
                    '#FFE6DE',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC3 Kiddy Team 2",
                colors: [
                    '#181000',
                    '#412000',
                    '#623100',
                    '#8B4100',
                    '#AC5200',
                    '#C56200',
                    '#D57300',
                    '#6AFFAC',
                    '#208B4A',
                    '#9C3100',
                    '#FF8373',
                    '#FFA494',
                    '#FFC5BD',
                    '#FFE6DE',
                    '#FFFFFF',
                ]
            },
            {
                name: "Black Tie",
                colors: [
                    '#181000',
                    '#412000',
                    '#623100',
                    '#8B4100',
                    '#AC5200',
                    '#C56200',
                    '#D57300',
                    '#525252',
                    '#202020',
                    '#9C3100',
                    '#FF8373',
                    '#FFA494',
                    '#FFC5BD',
                    '#FFE6DE',
                    '#FFFFFF',
                ]
            },
            {
                name: "White Tie",
                colors: [
                    '#181000',
                    '#412000',
                    '#623100',
                    '#8B4100',
                    '#AC5200',
                    '#C56200',
                    '#D57300',
                    '#FFFFFF',
                    '#C5C5C5',
                    '#9C3100',
                    '#FF8373',
                    '#FFA494',
                    '#FFC5BD',
                    '#FFE6DE',
                    '#FFFFFF',
                ]
            },
            {
                name: "Purple Tie",
                colors: [
                    '#181000',
                    '#412000',
                    '#623100',
                    '#8B4100',
                    '#AC5200',
                    '#C56200',
                    '#D57300',
                    '#CD62EE',
                    '#7B31D5',
                    '#9C3100',
                    '#FF8373',
                    '#FFA494',
                    '#FFC5BD',
                    '#FFE6DE',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC2 Frozen",
                colors: [
                    '#184AB4',
                    '#3973CD',
                    '#629CEE',
                    '#6AACF6',
                    '#7BBDFF',
                    '#8BD5FF',
                    '#9CDEFF',
                    '#DEF6FF',
                    '#3973CD',
                    '#6AC5FF',
                    '#9CDEFF',
                    '#B4E6FF',
                    '#C5EEFF',
                    '#DEF6FF',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC2 Reversed",
                colors: [
                    '#180020',
                    '#41006A',
                    '#6A00B4',
                    '#9C00FF',
                    '#B429FF',
                    '#CD52FF',
                    '#E67BFF',
                    '#EEACFF',
                    '#6A00B4',
                    '#B429FF',
                    '#C552FF',
                    '#D573FF',
                    '#E69CFF',
                    '#F6BDFF',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC2 Slow",
                colors: [
                    '#200808',
                    '#6A0800',
                    '#B40000',
                    '#F60000',
                    '#FF1800',
                    '#FF4A00',
                    '#FF6A00',
                    '#FF1800',
                    '#6A0800',
                    '#F60000',
                    '#F62910',
                    '#FF5229',
                    '#FF7339',
                    '#FF9C4A',
                    '#FFFFFF',
                ]
            },
            {
                name: "Golden",
                colors: [
                    '#9C6A08',
                    '#A47B10',
                    '#B48B18',
                    '#BD9C20',
                    '#C5AC29',
                    '#D5BD31',
                    '#DECD39',
                    '#FFFF52',
                    '#C59408',
                    '#C59408',
                    '#DECD39',
                    '#E6DE41',
                    '#F6EE4A',
                    '#FFFF52',
                    '#FFFFBD',
                ]
            },
            {
                name: "Monochrome",
                colors: [
                    '#393939',
                    '#4A4A4A',
                    '#525252',
                    '#626262',
                    '#737373',
                    '#7B7B7B',
                    '#8B8B8B',
                    '#D5D5D5',
                    '#414141',
                    '#626262',
                    '#8B8B8B',
                    '#A4A4A4',
                    '#BDBDBD',
                    '#D5D5D5',
                    '#EEEEEE',
                ]
            },
            {
                name: "GB Green",
                colors: [
                    '#103910',
                    '#103910',
                    '#103910',
                    '#103910',
                    '#316231',
                    '#316231',
                    '#316231',
                    '#8BB410',
                    '#103910',
                    '#316231',
                    '#316231',
                    '#8BB410',
                    '#8BB410',
                    '#8BB410',
                    '#8BB410',
                ]
            },
            {
                name: "GB Gray",
                colors: [
                    '#000000',
                    '#000000',
                    '#000000',
                    '#000000',
                    '#626262',
                    '#626262',
                    '#626262',
                    '#ACACAC',
                    '#000000',
                    '#626262',
                    '#626262',
                    '#ACACAC',
                    '#ACACAC',
                    '#ACACAC',
                    '#ACACAC',
                ]
            },
            {
                name: "GBC Retro Blast",
                colors: [
                    '#6A1800',
                    '#6A1800',
                    '#6A1800',
                    '#6A1800',
                    '#E67300',
                    '#E67300',
                    '#E67300',
                    '#FFBD73',
                    '#6A1800',
                    '#E67300',
                    '#E67300',
                    '#FFBD73',
                    '#FFBD73',
                    '#FFBD73',
                    '#FFBD73',
                ]
            },
        ],
        currentDefaultPaletteIndex: 0,
        colorGroupData: [
            {
                colorGroupName: "Fur",
                colorIndices: [0,1,2,3,4,5,6,9],
                indexOfMainColor: 2
            },
            {
                colorGroupName: "Skin",
                colorIndices: [10,11,12,13,14],
                indexOfMainColor: 11
            },
            {
                colorGroupName: "Tie",
                colorIndices: [7, 8],
                indexOfMainColor: 7
            }
        ],
        animations: [
            {
                animationName: "Walking",
                animationImages: [imageDKWalk_01, imageDKWalk_02, imageDKWalk_03, imageDKWalk_04, imageDKWalk_05, imageDKWalk_06, imageDKWalk_07, imageDKWalk_08, imageDKWalk_09, imageDKWalk_10, imageDKWalk_11, imageDKWalk_12, imageDKWalk_13, imageDKWalk_14, imageDKWalk_15, imageDKWalk_16, imageDKWalk_17, imageDKWalk_18, imageDKWalk_19, imageDKWalk_20],
                animationSeconds: 0.9
            },
            {
                animationName: "Rolling",
                animationImages: [imageDKRoll_01, imageDKRoll_02, imageDKRoll_03, imageDKRoll_04, imageDKRoll_05, imageDKRoll_06, imageDKRoll_07, imageDKRoll_08, imageDKRoll_09, imageDKRoll_10, imageDKRoll_11, imageDKRoll_12, imageDKRoll_13, imageDKRoll_14, imageDKRoll_15, imageDKRoll_16],
                animationSeconds: 0.75
            },
            {
                animationName: "Scratching Head",
                animationImages: [imageDKHit_01, imageDKHit_02, imageDKHit_03, imageDKHit_04],
                animationSeconds: 0.35
            }
        ],
        currentAnimationIndex: 0
    },
    {
        characterName: "Diddy Kong",
        yamlOptionName: 'Diddy',
        firstColorIndexInYamlOption: 1,
        additionalInfoOrInstructions: "",
        buttonColor: "#ff6565",
        buttonOutline: "#9e2727",
        buttonFontColor: "#111111",
        backgroundColorInCanvas: "#ffe0e0ff",
        backgroundColor: "#ffcbc7ff",
        palettes: [
            {
                name: "DKC2 Default",
                colors: [
                    '#311808',
                    '#522010',
                    '#6A3118',
                    '#944118',
                    '#B45220',
                    '#945239',
                    '#CD735A',
                    '#FF9C73',
                    '#FFB48B',
                    '#FFD59C',
                    '#AC1008',
                    '#D51810',
                    '#FF3120',
                    '#7B7B7B',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC2 Default (Inactive)",
                colors: [
                    '#291810',
                    '#392010',
                    '#4A2018',
                    '#623118',
                    '#7B3920',
                    '#623929',
                    '#835241',
                    '#AC6A52',
                    '#AC7B5A',
                    '#AC8B6A',
                    '#731010',
                    '#8B1810',
                    '#AC2018',
                    '#525252',
                    '#D5D5D5',
                ]
            },
            {
                name: "DKC2 Default (Invincible)",
                colors: [
                    '#834A31',
                    '#BD6239',
                    '#F67B4A',
                    '#FF9C52',
                    '#FFBD62',
                    '#FFBD94',
                    '#FFFFCD',
                    '#FFFFFF',
                    '#FFFFFF',
                    '#FFFFFF',
                    '#FF4131',
                    '#FF5239',
                    '#FF7B5A',
                    '#FFFFFF',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC2 Frozen",
                colors: [
                    '#184AB4',
                    '#3973CD',
                    '#629CEE',
                    '#6AACF6',
                    '#7BBDFF',
                    '#8BD5FF',
                    '#9CDEFF',
                    '#B4E6FF',
                    '#C5EEFF',
                    '#DEF6FF',
                    '#6AC5FF',
                    '#7BCDFF',
                    '#8BDEFF',
                    '#5AA4FF',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC2 Slow",
                colors: [
                    '#180800',
                    '#520000',
                    '#8B0000',
                    '#C50000',
                    '#FF0000',
                    '#FF2900',
                    '#FF4100',
                    '#FF5A00',
                    '#FF7300',
                    '#FF8B00',
                    '#AC1008',
                    '#D51810',
                    '#FF3120',
                    '#FF4100',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC2 Reversed",
                colors: [
                    '#080018',
                    '#200052',
                    '#410883',
                    '#6208BD',
                    '#8B10F6',
                    '#6218C5',
                    '#8B29D5',
                    '#B441E6',
                    '#DE52F6',
                    '#FF6AFF',
                    '#5A00BD',
                    '#8B20D5',
                    '#BD4AEE',
                    '#8B29D5',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC2 Team 2",
                colors: [
                    '#311808',
                    '#522010',
                    '#6A3118',
                    '#944118',
                    '#B45220',
                    '#945239',
                    '#CD735A',
                    '#FF9C73',
                    '#FFB48B',
                    '#FFD59C',
                    '#3100FF',
                    '#4A31FF',
                    '#7B5AFF',
                    '#7B7B7B',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC2 Team 2 (Inactive)",
                colors: [
                    '#291810',
                    '#392010',
                    '#4A2018',
                    '#623118',
                    '#7B3920',
                    '#623929',
                    '#835241',
                    '#AC6A52',
                    '#AC7B5A',
                    '#AC8B6A',
                    '#2008AC',
                    '#3929AC',
                    '#5241AC',
                    '#525252',
                    '#ACACAC',
                ]
            },
            {
                name: "DKC Team 2",
                colors: [
                    '#311808',
                    '#522010',
                    '#6A3118',
                    '#944118',
                    '#B45220',
                    '#945239',
                    '#CD735A',
                    '#FF9C73',
                    '#FFB48B',
                    '#FFD59C',
                    '#AC7300',
                    '#D5AC00',
                    '#FFE600',
                    '#7B7B7B',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC3 Kiddy",
                colors: [
                    '#311808',
                    '#522010',
                    '#6A3118',
                    '#944118',
                    '#B45220',
                    '#945239',
                    '#CD735A',
                    '#FF9C73',
                    '#FFB48B',
                    '#FFD59C',
                    '#5A6AAC',
                    '#6AACD5',
                    '#7BEEFF',
                    '#7B7B7B',
                    '#FFFFFF',
                ]
            },
            {
                name: "DKC3 Kiddy Team 2",
                colors: [
                    '#311808',
                    '#522010',
                    '#6A3118',
                    '#944118',
                    '#B45220',
                    '#945239',
                    '#CD735A',
                    '#FF9C73',
                    '#FFB48B',
                    '#FFD59C',
                    '#208B4A',
                    '#4AC57B',
                    '#6AFFAC',
                    '#7B7B7B',
                    '#FFFFFF',
                ]
            },
            {
                name: "GB Green",
                colors: [
                    '#103910',
                    '#103910',
                    '#103910',
                    '#316231',
                    '#316231',
                    '#316231',
                    '#8BB410',
                    '#8BB410',
                    '#8BB410',
                    '#8BB410',
                    '#316231',
                    '#8BB410',
                    '#8BB410',
                    '#316231',
                    '#8BB410',
                ]
            },
            {
                name: "GB Gray",
                colors: [
                    '#000000',
                    '#000000',
                    '#000000',
                    '#626262',
                    '#626262',
                    '#626262',
                    '#ACACAC',
                    '#ACACAC',
                    '#ACACAC',
                    '#ACACAC',
                    '#626262',
                    '#ACACAC',
                    '#ACACAC',
                    '#626262',
                    '#ACACAC',
                ]
            },
            {
                name: "GBC Retro Blast",
                colors: [
                    '#6A1800',
                    '#6A1800',
                    '#6A1800',
                    '#E67300',
                    '#E67300',
                    '#E67300',
                    '#FFBD73',
                    '#FFBD73',
                    '#FFBD73',
                    '#FFBD73',
                    '#E67300',
                    '#FFBD73',
                    '#FFBD73',
                    '#E67300',
                    '#FFBD73',
                ]
            },
            {
                name: "Golden",
                colors: [
                    '#9C6A08',
                    '#A47B10',
                    '#B48B18',
                    '#BD9C20',
                    '#C5AC29',
                    '#D5BD31',
                    '#DECD39',
                    '#E6DE41',
                    '#F6EE4A',
                    '#FFFF52',
                    '#C59408',
                    '#E6CD31',
                    '#FFFF52',
                    '#C59408',
                    '#FFFF52',
                ]
            },
            {
                name: "Monochrome",
                colors: [
                    '#101010',
                    '#313131',
                    '#4A4A4A',
                    '#737373',
                    '#9C9C9C',
                    '#6A6A6A',
                    '#8B8B8B',
                    '#ACACAC',
                    '#CDCDCD',
                    '#EEEEEE',
                    '#4A4A4A',
                    '#6A6A6A',
                    '#949494',
                    '#4A4A4A',
                    '#FFFFFF',
                ]
            },
            {
                name: "Sepia",
                colors: [
                    '#312010',
                    '#4A3120',
                    '#5A4131',
                    '#735241',
                    '#836A52',
                    '#7B6252',
                    '#A48B7B',
                    '#C5B4A4',
                    '#D5C5BD',
                    '#E6DED5',
                    '#5A4129',
                    '#6A5239',
                    '#836A5A',
                    '#947B6A',
                    '#FFFFFF',
                ]
            },
            {
                name: "SMB Mario",
                colors: [
                    '#BD3120',
                    '#BD3120',
                    '#BD3120',
                    '#6A7300',
                    '#6A7300',
                    '#6A7300',
                    '#EEA420',
                    '#EEA420',
                    '#EEA420',
                    '#EEA420',
                    '#6A7300',
                    '#EEA420',
                    '#EEA420',
                    '#6A7300',
                    '#EEA420',
                ]
            },
            {
                name: "SMB Luigi",
                colors: [
                    '#398B00',
                    '#398B00',
                    '#398B00',
                    '#EEA420',
                    '#EEA420',
                    '#EEA420',
                    '#FFFFFF',
                    '#FFFFFF',
                    '#FFFFFF',
                    '#FFFFFF',
                    '#EEA420',
                    '#FFFFFF',
                    '#FFFFFF',
                    '#EEA420',
                    '#FFFFFF',
                ]
            },
            {
                name: "Toothpaste",
                colors: [
                    '#002039',
                    '#003952',
                    '#005262',
                    '#006A7B',
                    '#008394',
                    '#009CA4',
                    '#00B4BD',
                    '#00CDD5',
                    '#00E6E6',
                    '#00FFFF',
                    '#5A5A5A',
                    '#A4A4A4',
                    '#E6E6E6',
                    '#5AACF6',
                    '#FFFFFF',
                ]
            },
            {
                name: "Whatsapp",
                colors: [
                    '#103100',
                    '#204A10',
                    '#316218',
                    '#417329',
                    '#5A8B39',
                    '#6AA441',
                    '#7BBD52',
                    '#8BD562',
                    '#9CE66A',
                    '#ACFF7B',
                    '#6AA441',
                    '#7BBD52',
                    '#8BD562',
                    '#316218',
                    '#ACFF7B',
                ]
            },
            {
                name: "Bubblegum",
                colors: [
                    '#6A0831',
                    '#7B2041',
                    '#8B395A',
                    '#9C4A6A',
                    '#AC6283',
                    '#BD739C',
                    '#CD8BAC',
                    '#DE9CC5',
                    '#EEB4DE',
                    '#FFC5F6',
                    '#7B2041',
                    '#8B395A',
                    '#9C4A6A',
                    '#B4416A',
                    '#FFC5F6',
                ]
            },
            {
                name: "Retro Frozen",
                colors: [
                    '#184AB4',
                    '#184AB4',
                    '#184AB4',
                    '#4A9CFF',
                    '#4A9CFF',
                    '#4A9CFF',
                    '#BDE6FF',
                    '#BDE6FF',
                    '#BDE6FF',
                    '#BDE6FF',
                    '#4A9CFF',
                    '#BDE6FF',
                    '#BDE6FF',
                    '#4A9CFF',
                    '#BDE6FF',
                ]
            },
            {
                name: "Retro Reversed",
                colors: [
                    '#41006A',
                    '#41006A',
                    '#41006A',
                    '#9C29DE',
                    '#9C29DE',
                    '#9C29DE',
                    '#E67BFF',
                    '#E67BFF',
                    '#E67BFF',
                    '#E67BFF',
                    '#9C29DE',
                    '#E67BFF',
                    '#E67BFF',
                    '#9C29DE',
                    '#E67BFF',
                ]
            },
            {
                name: "Retro Slow",
                colors: [
                    '#6A0800',
                    '#6A0800',
                    '#6A0800',
                    '#FF1800',
                    '#FF1800',
                    '#FF1800',
                    '#FF6A00',
                    '#FF6A00',
                    '#FF6A00',
                    '#FF6A00',
                    '#FF1800',
                    '#FF6A00',
                    '#FF6A00',
                    '#FF1800',
                    '#FF6A00',
                ]
            },
            {
                name: "Rottytops",
                colors: [
                    '#082020',
                    '#103131',
                    '#104139',
                    '#18524A',
                    '#206252',
                    '#207362',
                    '#298373',
                    '#31947B',
                    '#31AC8B',
                    '#39BD9C',
                    '#4A0073',
                    '#6A2994',
                    '#8B41B4',
                    '#206252',
                    '#FFFFFF',
                ]
            },
        ],
        currentDefaultPaletteIndex: 0,
        colorGroupData: [
            {
                colorGroupName: "Fur",
                colorIndices: [0,1,2,3],
                indexOfMainColor: 3
            },
            {
                colorGroupName: "Skin",
                colorIndices: [4,5,6,7,8,9],
                indexOfMainColor: 8
            },
            {
                colorGroupName: "Clothes",
                colorIndices: [10,11,12],
                indexOfMainColor: 11
            }
        ],
        animations: [
            {
                animationName: "Walking",
                animationImages: [imageDiddyWalk_01, imageDiddyWalk_02, imageDiddyWalk_03, imageDiddyWalk_04, imageDiddyWalk_05, imageDiddyWalk_06, imageDiddyWalk_07, imageDiddyWalk_08, imageDiddyWalk_09, imageDiddyWalk_10, imageDiddyWalk_11, imageDiddyWalk_12, imageDiddyWalk_13, imageDiddyWalk_14, imageDiddyWalk_15, imageDiddyWalk_16],
                animationSeconds: 0.9
            },
        ],
        currentAnimationIndex: 0
    }
];